config:
  MD013: false  # Line length
  MD024: false  # Multiple headings with the same content (CHANGELOG)
  MD033: false  # Allow inline HTML
  MD041: false  # First line in file should be a top level header

globs:
  - "**/*.md"

ignores:
  - "node_modules"
  - ".venv"
