config:
  MD009: false  # Trailing spaces
  MD012: false  # Multiple consecutive blank lines
  MD013: false  # Line length
  MD022: false  # Headings should be surrounded by blank lines
  MD024: false  # Multiple headings with the same content (CHANGELOG)
  MD026: false  # Trailing punctuation in heading
  MD031: false  # Fenced code blocks should be surrounded by blank lines
  MD032: false  # Lists should be surrounded by blank lines
  MD033: false  # Allow inline HTML
  MD036: false  # Emphasis used instead of heading
  MD040: false  # Fenced code language
  MD041: false  # First line in file should be a top level header
  MD060: false  # Table column style

globs:
  - "**/*.md"

ignores:
  - "node_modules"
  - ".venv"
  - ".pixi"
